### ISSUE TITLE
Make RAVEN into a Matlab toolbox

### ISSUE THREAD

**Issue by rasmusagren** [SysBioChalmers/RAVEN#16]
A main drawback with Matlab compared to, say, Python or R is that there is no convenient way to package and install code. Matlab still depends on manually handling a list of search paths, which feels ancient compared to the advanced package managers such as pip or conda used by its competitors.

Mathworks have recently taken a small step in that direction, and as of  R2016a there are APIs for packaging and installing toolboxes (http://se.mathworks.com/help/matlab/ref/matlab.addons.toolbox.installtoolbox.html). If you were able to write `matlab.addons.toolbox.installToolbox('https://se.mathworks.com/matlabcentral/fileexchange/raven=0.8')` just as you write `install.packages()` in R that would be really nice. It would also allow you to work more portable in that you can move between local/cluster/cloud and still be sure that the environment is the same.

I just put this here because I stumbled upon it, maybe someone wants to give it a shot at one point..

**Comment by simas232** [comment]
Having RAVEN as the packaged Matlab toolbox is advantegous, because the toolbox itself would be automatically added to Matlab pathlist. However, the installation process would still be semi-automatic as the user would need to install libSBML MATLAB API and solver software manually. It's possible to include libSBML in future RAVEN versions, but as for solver software, an open-source program must be implemented in RAVEN.

We can therefore come back to this question as soon as we have any open source solver sofware implemented in RAVEN.

**Comment by edkerk** [comment]
We will not implement an open source solver (#30), plus turning RAVEN into a MATLAB toolbox requires resources we do not have at the moment.
