### ISSUE TITLE
help: importExcelModel fails importing metMiriams

### ISSUE THREAD

**Issue by HMbio** [SysBioChalmers/RAVEN#179]
Hello every one 
I tried to install RAVEN 2.0.3 on matlab in order to use it for metabolic genome scale simulations of microbial communities but I faced difficulties doing so and I was not able run matlab codes.
The error in installation RAVEN toolbox is as follow:

when I type checkInstallation in matlab command window

Checking if it is possible to parse a model in Microsoft Excel format... FAILED
 
and error I get when trying to run a code is 

```matlab
Undefined function or variable 'index'.

Error in importExcelModel>parseMiriam (line 853)
            index

Error in importExcelModel (line 707)
    model.metMiriams=parseMiriam(model.metMiriams);

Error in SBMLFromExcel (line 30)
model=importExcelModel(fileName,false,printWarnings);

Error in Main (line 41)
SBMLFromExcel(draftFile,tmp);

Error in run (line 96)
evalin('caller', [script ';']);
```

I am using MATLAB R2016a. Thank you for your time and attention

**Comment by edkerk** [comment]
@HMbio Looking at line 853 of `importExcelModel` I don't immediately see how this could fail. A few additional questions:
- What kind of operating system are you running?
- When you run SBMLFromExcel, what file are you using?
- Do the metMiriams in that Excel file have a strange format?

Before you run `SBMLFromExcel` (or directly `importExcelModel`, because that is where the problem seems to be), can you select Editor --> Breakpoints --> Pause on Errors ? When the error occurs, can you post what is stored in `I`?

**Comment by edkerk** [comment]
No reply after >1 year, issue assumed to be solved.
