### ISSUE TITLE
Is it possible to draw metabolic map with the help of RAVEN? any coding is available for that.

### ISSUE THREAD

**Issue by kabilan2818** [SysBioChalmers/RAVEN#221]
### Description of the issue:
*Try to be as clear as possible, e.g.:
- Is there a functionality missing?
- Did an existing function fail?
- What is the exact error message, and other output that you got?
- What have you tried yourself to fix it?

#### Reproducing this issue:
*If applicable, please attach the problematic code. PLEASE DELETE THIS LINE.*
```matlab
INSERT CODE HERE
```

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?)
2. Operating system (Windows/Mac/Linux; include version)

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

**Comment by edkerk** [comment]
@kabilan2818 please format your posts using the template. Also, you might find it helpful to ask such questions in the Gitter chatroom: https://gitter.im/SysBioChalmers/RAVEN

**Comment by simas232** [comment]
@kabilan2818, the RAVEN toolbox does not have any functions to draw the pathways. Instead, you can create a pathway layout on your own using e.g. CellDesigner and then open the XML file using the function `constructPathwayFromCelldesigner`. You can also find several pre-built metabolic pathways in [CellDesigner website](http://celldesigner.org/models.html#).

Since this question is solved, I am closing this issue. As @edkerk already wrote, the most appropriate way to ask about RAVEN functions is through [Gitter](https://gitter.im/SysBioChalmers/RAVEN). One should create a new issue only if experiencing any errors or unexpected results while using RAVEN.
