### ISSUE TITLE
bug: error in xml_parseany in MATLAB 2014b+

### ISSUE THREAD

**Issue by kabilan2818** [SysBioChalmers/RAVEN#283]
tried to construct pathway using xml file bur it shows the below error. Could u help in this regards

```matlab
pathway = constructPathwayFromCelldesigner('carbohydrate metabolism.xml')
The P-code file C:\Users\Kabilan\Documents\MATLAB\RAVEN-master\software\xml_toolbox\xml_parseany.p was generated prior to
MATLAB version 7.5 (R2007b) and is no longer supported. Use pcode to regenerate the file using MATLAB R2007b or later.

Error in constructPathwayFromCelldesigner (line 81)
v = xml_parseany(fileread(inputFile));
```
v = xml_parseany(fileread('carbohydrate metabolism.xml'))
The P-code file C:\Users\Kabilan\Documents\MATLAB\RAVEN-master\software\xml_toolbox\xml_parseany.p was generated prior to
MATLAB version 7.5 (R2007b) and is no longer supported. Use pcode to regenerate the file using MATLAB R2007b or later.

**Comment by edkerk** [comment]
Thanks for reporting this. Could you please provide a link to the XML file so we can try to replicate this?

**Comment by kabilan2818** [comment]
https://github.com/SysBioChalmers/Yeast-maps/tree/master/SBMLfiles/Carbohydrate%20metabolism


from this i have taken xml file.

**Comment by edkerk** [comment]
The problem lies with XML Toolbox no longer being supported by MATLAB 2014b and later, also see comments [here](https://se.mathworks.com/matlabcentral/fileexchange/4278-xml-toolbox). [tinyxml2](http://www.mathworks.com/matlabcentral/fileexchange/48308-tinyxml2-wrapper) is suggested as alternative toolbox, but this does not support the `xml_parseany()` functionality that is required by `constructPathwayFromCelldesigner`. Attempting to fix this would probably take considerable effort, while this function seems to be rarely used.
