### ISSUE TITLE
bug: setParam multiple objective functions

### ISSUE THREAD

**Issue by anoop1988** [SysBioChalmers/RAVEN#350]
Hi,
I am using RAVEN tool kit for GEM reconstruction based gene expression data. But I am getting error in getINITModel2. Given below the code. Could someone help me to find the probolem,

params.MSK_DPAR_OPTIMIZER_MAX_TIME = 30000; % added for Mosek 7
params.MSK_DPAR_MIO_TOL_REL_GAP    = 0.02;  % added for Mosek 7

addpath(genpath('Human-GEM/'))
addpath(genpath('RAVEN-master/'))
addpath(genpath('mosek/'))
 
initCobraToolbox(false) 
changeCobraSolver ('gurobi', 'all');
%% Import the ref model
model=load('Human-GEM.mat'); 
model= addBoundaryMets(model.ihuman);
model=setParam(model, 'obj', 'HMR_3964', 1);
essentialTasks = parseTaskList('metabolicTasks_Essential.xlsx');
checkTasks(model, [], true, false, false, essentialTasks)
%% read data
New_exp= readtable('TPM.txt', 'Format','%s %f');
New.tissues={'pbmc'};
New.genes=New_exp.ID;
New.levels=table2array(New_exp(:,'TPM'));
New.threshold=1;

newGEM=getINITModel2(model, 'pbmc', [], [], New, [], true, [], true, true, essentialTasks, [], []);

Error -
Error in setParam (line 94)
            model.c(indexes(j))=params(j);

Error in getEssentialRxns (line 39)
        sol=solveLP(setParam(model,'obj',rxnsToCheck,-1));

Error in checkTasks (line 221)
                [~, taskEssential]=getEssentialRxns(tModel);

Error in getINITModel2 (line 302)
        [taskReport, essentialRxnMat]=checkTasks(cModel,[],printReport,true,true,taskStructure);

Error in Cmd (line 36)
newGEM=getINITModel2(model, 'pbmc', [], [], New, [], true, [], true, true, essentialTasks, [], []);

**Comment by simas232** [comment]
@anoop1988, RAVEN does not have a function called `getINITModel2`. Could you please give more information e.g. how this function is different than `getINITModel`? Also, it would be great if you share the output you get when running `checkInstallation()`.

**Comment by JonathanRob** [comment]
@simas232 `getINITModel2` is from the `Human-GEM` repo.

@anoop1988, I think the issue comes from the solver parameters you're trying to set. It seems that you are setting Mosek parameters, but using Gurobi as the solver. Valid Gurobi parameters (in the `params` structure) are, for example, `TimeLimit`, `MIPGap`, `FeasibilityTol`, `OptimalityTol`. There are likely more, but maybe @simas232 or someone else can assist you with setting these solver parameters -- assuming this is the source of the error.

**Comment by edkerk** [comment]
It is not related to the `params` structure, as it is actually nowhere used as input. Also, the error in `setParam` does not have to do with solver parameters, but setting the objective function in the model. However, I'm not sure what is actually happening.

Could you please run `essRxns=getEssentialRxns(model)`, so run it directly on the Human-GEM?

**Comment by edkerk** [comment]
Not sure that is actually good or bad :), but at least it didn't throw a similar error as before. So `getEssentialRxns` and the functions it call are fine, and so is the model that you start with. Then the problem seems to be with the `checkTasks`/`getINITModel2` part. Perhaps there is something with the tasklist or the data, such that the model that is eventually parsed to `getEssentialRxns` is faulty. @JonathanRob, do you spot anything suspicious around the input?

**Comment by JonathanRob** [comment]
It's hard to tell from this where the error is coming from, but I also suspect something with the tasks. What did the output of the `checkTasks(model, [], true, false, false, essentialTasks)` command look like, @anoop1988 ?

**Comment by anoop1988** [comment]
This is output from checkTasks()
PASS: [ER] Aerobic rephosphorylation of ATP from glucose
PASS: [ER] Aerobic rephosphorylation of GTP
PASS: [ER] Aerobic rephosphorylation of CTP
PASS: [ER] Aerobic rephosphorylation of UTP
PASS: [BS] ATP de novo synthesis
PASS: [BS] CTP de novo synthesis
PASS: [BS] GTP de novo synthesis
PASS: [BS] UTP de novo synthesis
PASS: [BS] dATP de novo synthesis
PASS: [BS] dCTP de novo synthesis
PASS: [BS] dGTP de novo synthesis
PASS: [BS] dTTP de novo synthesis
PASS: [SU] Histidine uptake
PASS: [SU] Isoleucine uptake
PASS: [SU] Leucine uptake
PASS: [SU] Lysine uptake
PASS: [SU] Methionine uptake
PASS: [SU] Phenylalanine uptake
PASS: [SU] Threonine uptake
PASS: [SU] Tryptophan uptake
PASS: [SU] Valine uptake
PASS: [IC] Glycerate 3-phosphate  de novo synthesis
PASS: [IC] Mitochondrial acetyl-CoA de novo synthesis
PASS: [IC] Mitochondrial AKG de novo synthesis
PASS: [IC] Erythrose 4-phosphate de novo synthesis
PASS: [IC] Fructose 6-phosphate de novo synthesis
PASS: [IC] Glyceraldehyde 3-phosphate de novo synthesis
PASS: [IC] Glucose 6-phosphate de novo synthesis
PASS: [IC] Mitochondrial oxaloacetate de novo synthesis
PASS: [IC] Phosphoenolpyruvate de novo synthesis
PASS: [IC] Pyruvate de novo synthesis
PASS: [IC] Ribose 5-phosphate de novo synthesis
PASS: [IC] Mitochondrial succinyl-CoA de novo synthesis
PASS: [BS] Cholesterol de novo synthesis
PASS: [BS] Protein synthesis from AAs
PASS: [ER] Oxidative phosphorylation
PASS: [ER] Oxidative decarboxylation
PASS: [ER] Krebs cycle NADH
PASS: [ER] Ubiquinol-to-proton
PASS: [ER] Ubiquinol-to-ATP
PASS: [SU] Beta oxidation of saturated FA
PASS: [SU] Beta oxidation of long-chain FA
PASS: [SU] Beta oxidation of odd-chain FA
PASS: [SU] Beta oxidation of unsaturated fatty acid (n-9) 
PASS: [SU] Beta oxidation of unsaturated fatty acid (n-6) 
PASS: [SU] Uptake and beta oxidation of all NEFAs
PASS: [SU] Choline uptake
PASS: [SU] Inositol uptake
PASS: [BS] Phosphatidylcholine de novo synthesis
PASS: [BS] Phosphatidylethanolamine de novo synthesis
PASS: [BS] Phosphatidylserine de novo synthesis
PASS: [BS] Phosphatidylinositol de novo synthesis
PASS: [BS] Thiamin phosphorylation to TPP
PASS: [BS] Coenzyme A synthesis from pantothenate
PASS: [BS] FAD synthesis from riboflavin
PASS: [BS] Heme biosynthesis
PASS: [GR] Growth on Ham's media (biomass production)

ans = 

  struct with fields:

             id: {57×1 cell}
    description: {57×1 cell}
             ok: [57×1 logical]

**Comment by JonathanRob** [comment]
Ok, that looks fine. Try running the below command:
`[taskReport, essentialRxnMat] = checkTasks(model, [], true, false, true, taskStructure);`

It will likely take some time to run, unfortunately, but should help narrow down the source of the error.

**Comment by anoop1988** [comment]
It also gives error,

Index exceeds the number of array elements (1).

Error in setParam (line 94)
            model.c(indexes(j))=params(j);

Error in getEssentialRxns (line 39)
        sol=solveLP(setParam(model,'obj',rxnsToCheck,-1));

Error in checkTasks (line 221)
                [~, taskEssential]=getEssentialRxns(tModel);

Error in Covid (line 47)
[taskReport, essentialRxnMat] = checkTasks(ihuman, [], true, false, true, taskStructure);

**Comment by JonathanRob** [comment]
Ok, I think I finally found the source of the problem.

@edkerk, a change was recently made to `setParam` (f68090a). This change made the following usage of the `setParam` function erroneous:

`model = setParam(model, 'obj', rxns, 1);`

where `rxns` is a vector of reactions with length > 1. It seems that the change to the function prevents assigning a single value (1) to several items. This could/should probably be fixed by adding the following code near the top of the function (which is just a copy of how `paramType` is handled):

```
if length(rxnList)>1 && length(params)==1
    paramType(1:length(rxnList))=params;
end
```

However, this does not completely fix the problem, as specifying `'obj'` for the `paramType` will not assign it as expected. I copied the relevant code from `setParam` below (lines 90-95):

```
if strcmpi(paramType{j},'obj')
    %NOTE: The objective is changed to the new parameters, they are not
    %added
    model.c=zeros(numel(model.c),1);
    model.c(indexes(j))=params(j);
end
```

Note that with the new way in which `setParam` iterates through this section, it will reset `model.c` with every iteration. As a result, if I try to change the value of `model.c` for a list of several reactions, it will only change it for the last reaction in the list.

I didn't want to edit the function myself, in case I break something else. But let me know if you need help.

@anoop1988, we will need to fix the `setParam` function before your script will work, unfortunately.

**Comment by edkerk** [comment]
@JonathanRob Nice detective work! What would probably solve this is to move the zero'ing of `model.c` outside of that loop? 

```matlab
if ~isempty(indexes)
    if contains(paramType,'obj')
        model.c=zeros(numel(model.c),1);
    end
    for j=1:length(paramType)
        if strcmpi(paramType{j},'eq'
    [...]
        if strcmpi(paramType{j},'obj')
            model.c(indexes(j))=params(j);
        end
```

**Comment by edkerk** [comment]
And that is of course in addition to the proposed handling of `params` in the top of the function.

**Comment by anoop1988** [comment]
Thank you, its working now.
