### ISSUE TITLE
help: permission denied to use euk100_kegg94

### ISSUE THREAD

**Issue by joel8484** [SysBioChalmers/RAVEN#365]
Hi there,

I was following the tutorials and in tutorial 5 where we have to use the pre-defined HMMs where we use euk100_kegg94, I downloaded it and moved it to the RAVEN directory where all the dependencies are stored. However, when I ran the first command `getKEGGModelForOrganism` I got an error that the Permission to unzip the eukaryote HMM file was denied. I tried changing the file permissions as well. Then later discovered that the file on matlab was higlighted as "Not under Source control". When I right clicked on it, I got a GIT error - Missing commit <followed by a long code>. I keep getting the same error of Permission denied when trying to run get KEGGModelForOrganism. 

Regards,
Joel

**Comment by edkerk** [comment]
Could you please use the "New issue template"? This would give us (1) the exact command that you use; (2) your version of RAVEN; MATLAB; OS; and please also report the exact error message that you get, so we can try to replicate what you observe!

**Comment by joel8484** [comment]
Hi Eduard,

Thanks for the reply. Below I have tried my best to give a description for the issue which I am facing. 

### Description of the issue:

- Is there a functionality missing?
Yes, a few of them I would like to mention here: for LP solver while running RAVEN because I have some issues I think might be because of running gurobi in a docker container. As per the tutorials the installation of gurobi requires to have a gurobi license key and to enter the command grbgetkey <followed by the license key>. Since I'm using a Docker container (ubuntu) it is required to have a WLS token and get a separate license file, it doesn't seem to have the license key with it (using a WLS token and a new associated license file was suggested by the gurobi support team)? 
Second: checkInstallation gives one NOT OK flag for cd-hit which I believe is useful for running the command getKEGGModelForOrganism. The following is the flag which shows on checkInstallation `Checking non-essential/development binary executables:
NOTE: Only fix these binaries if planning to use KEGG FTP dump files in getKEGGModelForOrganism
	cd-hit...								Not OK! If necessary, download/compile the binary and run checkInstallation again`
- Did an existing function fail?
Yes - getKEGGModelForOrganism gave an error while doing tutorial 5.
- What is the exact error message, and other output that you got?
>> model=getKEGGModelForOrganism('sce','sce.fa','euk100_kegg94','output',false,false,false,false,10^-30,0.8,0.3,-1);


*** The model reconstruction from KEGG based on the protein homology search against KEGG Orthology specific HMMs ***

Extracting the HMMs archive file... Error using getKEGGModelForOrganism (line 370)
Permission denied

- What have you tried yourself to fix it?
I presumed there were restrictions on the HMM archive euk100_kegg94, so I only changed the read,write,execute permissions for it. I did not find any other solution for it

#### Reproducing this issue:
```matlab
INSERT CODE HERE

```

#### System information
* Please report:
1. RAVEN version - THE RAVEN TOOLBOX v.2.5.1
2. Operating system - Ubuntu 18.04.5

**I hereby confirm that I have:**
- [ X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

Thanks and Regards,
Joel

**Comment by edkerk** [comment]
1. Regarding gurobi unfortunately we cannot do more than refer to gurobi.com, and it seems like you have been in contact with them. As an alternative, have you tried installing [COBRA Toolbox](https://github.com/opencobra/cobratoolbox/) and setting `setRavenSolver('cobra')`, as it can use the open-source *glpk* solver that comes with COBRA Toolbox? We are currently working on implementing *glpk* directly in RAVEN, but this is still a little while away.
2. The *cd-hit* issue has also been mentioned [here](https://github.com/SysBioChalmers/RAVEN/issues/354). We haven't figured out yet how to solve this, but this is a non-essential binary that is only required to generate new HMM files when a new version of KEGG is released.
3. It indeed seems like MATLAB is not given access to the downloaded ZIP file, which seems not RAVEN specific. I don't know how to solve that problem directly, but as an alternative, can you try the following:
3.1. Remove the existing `euk100_kegg94.zip` file.
3.2. 'Manually' (in the browser, or using `wget` in the Docker terminal?) download the zip file from [here](https://chalmersuniversity.box.com/shared/static/754bdz0965261fktzlwc77rcv7me87i6.zip).
3.3. Unzip the downloaded `euk100_kegg94.zip` file to your favourite folder.
3.4. In MATLAB, set the working directory to the folder that contains the unzipped file (e.g. `/my/favourite/dir/`, which then contains the unzipped `euk100_kegg94` folder).
3.5. Rerun `getKEGGModelForOrganism` with `'euk100_kegg94'` as `dataDir`, as you did before. 

Point 3.4 is important as it will then automatically find the unzipped folder, instead of downloading and unzipping it again.

**Comment by joel8484** [comment]
Hi Eduard,

I followed your provided steps and it worked perfect for me. Althought for the Permission denied errors what I did was to change the permission for the entire RAVEN folder using `chmod -R a+rwx RAVEN` and this cleared a bit of air for me. Next I ran tutorial 6 which is of my interest for my work in using RAVEN to make metabolic reconstructions for 100 prokaryote strains. Since, it would be laboursome and time consuming to create 100 reconstructions, I wanted to know whether there is any way I can parallelize this to get multiple reconstructions at the same time? If yes then, could you share the command or a template which entails the commands for the same? I thank you very much working me through with this issue. 

Many thanks and Regards,
Joel

**Comment by edkerk** [comment]
The link you refer to is indeed suitable for prokaryotes.

There is no built-in code to parallelize model generation, you should probably write a script with `for` loops to go through the 100 strains one by one. From tutorial 6 I suggest you only run `line 49`, the HMM-based search, as the MetaCyc approach (`line  30`) often gives false positives and requires manual curation that is not feasible for 100 models.

I will close this Issue, as the original problem is resolved. However, do have a look at PR #369, as it contains code that would speed-up running `getKEGGModelForOrganism` for many strains/species.
