### ISSUE TITLE
exported model cannot be imported in any other tool

### ISSUE THREAD

**Issue by Sanrrone** [SysBioChalmers/RAVEN#423]
Dears,
I tried to correct a model using raven, but when I tried to export the model (`exportModel(model)`) the next software doesn't work. When I said next software it could be cobrapy, memote or carveme.

I tried a minimal example which is load my "well defined model" (other softwares can read it without errors).
```
model=importModel('infantis.xml')
exportModel(model, 'testout')


```
after I have my testout.xml I cannot use it for postprocessing and all related errors are about the sbml model (not valid).
I attached my infantis.xml in case you could reproduce the error.
[infantis.zip](https://github.com/SysBioChalmers/RAVEN/files/8898291/infantis.zip)

thanks in advance!
PD: we need more tutorials, it is not easy to handle with the metabolic toolboxes world.

#### System information
1. RAVEN version 2.7.1
2. Ubuntu 18.04 4.15.0-176-generic

**I hereby confirm that I have:**

- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by edkerk** [comment]
Thank you for reporting the issue encountered and providing the file that you struggled with (it helps us a lot to find what causes the problem!).

First, the `infantis.xml` is not valid SBML when run through the [Online SBML Validator](https://synonym.caltech.edu/validator_servlet/index.jsp) (there are missing `boundaryCondition` and `constant` attributes for each metabolite), but I see that this file was derived from CarveMe, so this is not because of RAVEN. Rather, even though the SBML is invalid, RAVEN still allows you to load it, and when you use `exportModel` it correctly adds the two missing attributes.

When running the `testout.xml` file through the Online SBML Validator, the only error is that no objective is given. This might be why other softwares are not allowing the model to be loaded (RAVEN is more forgiving and still allows you to load the model). A solution would be to set the `growth` reaction as objective function (`model=setParam(model,'obj','growth',1);`). The resulting file is valid SBML and should also be loaded in softwares that strictly require valid SBML files.

Meanwhile, you should also pay attention to the other warnings that are shown when importing/exporting the model, in particular:
```matlab
WARNING: The following metabolites already exist in the same compartment:
	L Arabinitol C5H12O5[c]
	L Arabinitol C5H12O5[e]
	Oxidized ferredoxin[c]
	D-Glucose[c]
```

**Comment by edkerk** [comment]
If you confirm that the new SBML file is valid ([here](https://synonym.caltech.edu/validator_servlet/index.jsp)), then you can ask `memote` why the model fails.

Did you find the `tutorial` subfolder that comes with RAVEN? They're quite old, but might still be useful. Otherwise, you might appreciate [this book chapter](https://www.biorxiv.org/content/10.1101/2021.06.18.448943v1.full) which showcases a brief protocol to make a draft model.

**Comment by Sanrrone** [comment]
I notice the model still lack of the "growth"
```
>>model=setParam(model,'obj','growth',1)
WARNING: Reaction growth is not present in the reaction list
```
So invalid sbml format is still appearing.

I also tried a new approach following the tutorial5 from RAVEN repository as you mention. But, at the end, saving the model (just after the gapfilling), uploading the xml file to https://synonym.caltech.edu/validator_servlet/index.jsp with no success. But this time I got the errors: 
```
 Line 3458 Column 140: (SBML Validation Rule #fbc-20303) The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V3 Section 3.4 Encountered '(' when expecting a capital letter.The chemicalFormula '(C12H20O10)n' has incorrect syntax.

<species metaid="M_C00369" sboTerm="SBO:0000247" id="M_C00369" name="Starch" compartment="s" initialConcentration="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false" fbc:chemicalFormula="(C12H20O10)n">
```
all errors comes from a wrong chemical formula. How can I fix them?

PD: biorxiv book chapter help to undestand with a whole exercise when you have biomass data, unfortunately didn't help me in my beginnings where I am looking just to create a "general" model from my proteins, validate it, and check what they are producing.

**Comment by edkerk** [comment]
Apologies, that should have been capitalized: `model=setParam(model,'obj','Growth',1)`, but notice that this just refers to a reaction with the identifier "Growth". If the reaction ID would be different, then also the reference to it here should be different.

What you encounter from tutorial5 is that the chemical formula of polymeric metabolites (e.g. starch) includes an 'n' to indicate the repeating monomer (and brackets `()` around the monomer). However, 'n' is not a chemical element (and neither are brackets), so that SBML FBC throws an error. You could for instance remove the 'n' from these formulas (e.g. `model.metFormulas=regexprep(model.metFormulas,'\(|\)|n','');`, haven't tested this).

**Comment by Sanrrone** [comment]
thanks a lot!. both tricks allow me to import the model, do some stuffs on it and export a refined model. Setting the parameter 'Growth' do the trick as you mention.
