### ISSUE TITLE
Flux direction of mean flux, in random sampling

### ISSUE THREAD

**Issue by johanbj** [SysBioChalmers/RAVEN#48]
Running the randomSampling.m script on a model with all reaction lower boundaries set to 0 and with all reactions non-reversible still rendered negative mean fluxes. "Muting" lines 59-62 in the script seems to solve the problem completely.

**Comment by Hao-Chalmers** [comment]
Since you defined the model with 'biologically relevant' bounds (lb=0) in simulation, in which case the third parameter 'replaceBoundsWithInf' should be set as false (this is equivalents to 'Muting lines 59-62'). This information can be found from the help message.

So everything should be fine if you do such: solutions=randomSampling(model, 1000, 0);

**Comment by edkerk** [comment]
As Hao mentioned, using replaceBoundsWithInf = false indeed has the same effect.

Nonetheless, just because you have lb=0 for all reactions doesn't mean your model only has biological relevant bounds (you can still have ub=1000, which is not biological relevant!). So you shouldn't be motivated to set replaceBoundsWithInf = false, based on the documentation.

Regardless, this is a small bug that I'll fix right away.

**Comment by edkerk** [comment]
Fixed in 230e4a79f15e4899124a5eaa7cf144313b082b21

**Comment by johanbj** [comment]
Very clear explanation, thank you for the help!
